---
  - name: Install common packages
    apt:
      name: "{{ item }}"
      update_cache: yes
      cache_valid_time: 3600
      state: latest
    with_items:
      - git
      - python
      - python3
      - nfs-common
      - net-tools
      - htop
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      